//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBakaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int id { get; set; }
        public Nullable<int> idSchedule { get; set; }
        public Nullable<int> row { get; set; }
        public Nullable<int> place { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual schedule schedule { get; set; }
        public virtual users users { get; set; }
    }
}
